version: '3'

services:
  server:
    build:
      context: ./
      dockerfile: flask.dockerfile
    volumes:
      - keyforge-database:/app/db
  bot:
    build:
      context: ./
      dockerfile: telegram.dockerfile
    depends_on:
      - server
    volumes:
      - ./bot:/app:rw
  # [DEV] OPTIONAL: sqlite web client
  sqlite:
    image: sqrt3/sqlite-web
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - keyforge-database:/db
    command: /db/keyforge.db

volumes:
  keyforge-database:
