version: '3'

services:
  server:
    build:
      context: ./
      dockerfile: flask.dockerfile
  bot:
    build:
      context: ./
      dockerfile: telegram.dockerfile
    depends_on:
      - server
    volumes:
      - ./bot:/app:rw
    ports:
      - "80:80"
